### ISSUE TITLE
Autocomplete is not working

### ISSUE THREAD

**Issue by felipecrrmts** [templ-go/templ-jetbrains#2]

**Comment by mhrlife** [comment]
I discovered these logs in the idea log file:
OS: Windows - using WSL2

```
2023-12-17 13:09:28,880 [   8604]   INFO - #c.i.p.l.i.LspServerImpl - TemplLspServerDescriptor@keeam(RUNNING;0): Starting server
2023-12-17 13:09:29,026 [   8750]   INFO - #c.i.p.l.a.LspServerDescriptor - TemplLspServerDescriptor@keeam: starting LSP server: C:\Program Files\JetBrains\GoLand 2023.2.4\jbr\bin [lsp]
2023-12-17 13:09:29,052 [   8776]   WARN - #c.i.p.l.i.LspServerImpl - TemplLspServerDescriptor@keeam(RUNNING;0): Failed to start server
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\Program Files\JetBrains\GoLand 2023.2.4\jbr\bin": CreateProcess error=5, Access is denied
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:356)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:84)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:95)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.java:19)
	at com.intellij.platform.lsp.impl.LspServerImpl.k(LspServerImpl.java:377)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Cannot run program "C:\Program Files\JetBrains\GoLand 2023.2.4\jbr\bin": CreateProcess error=5, Access is denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:432)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:346)
	... 15 more
Caused by: java.io.IOException: CreateProcess error=5, Access is denied
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 18 more
```
	
Then I checked the plugin's code and I saw it utilized gobin to the templ.exe. I installed Go on windows and configured GOBIN property and the last error disappeared. However, now I get this error:
```
2023-12-17 13:33:46,131 [  12294] SEVERE - #o.j.c.AsyncPromise - Element: class com.intellij.psi.impl.source.tree.PsiPlainTextImpl #TEXT  because: File language:Language: TEXT != Provider base language:Language: templ
invalidated at: see attachment
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiPlainTextImpl #TEXT  because: File language:Language: TEXT != Provider base language:Language: templ
invalidated at: see attachment
```

**Comment by belliel** [comment]
bump

**Comment by bastianwegge** [comment]
@mhrlife I get the same error for macOS

```
2023-12-13 22:03:58,605 [25104414]   WARN - #c.i.p.l.i.LspServerImpl - TemplLspServerDescriptor@aaa_workspace(RUNNING;0): Failed to start server
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/": error=13, Permission denied
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:356)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:84)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:95)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.java:19)
	at com.intellij.platform.lsp.impl.LspServerImpl.k(LspServerImpl.java:377)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Cannot run program "/": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:432)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:346)
	... 15 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 18 more
```

So basically the LSP-Integration isn't working yet. Is there anything we can do to speed things up here? 👼

**Comment by bastianwegge** [comment]
To fix this error:

Step 1: Plugin Configuration
- Open the settings inside of GoLand
- Go to the Templ Settings page (search templ in the top left)
- Insert your `LSP Path`

Step 2: Environment Settings
- It seems to me there's an issue with the environment you get when you start GoLand using the Toolbox or using the scripts you can generate (the one where you can type `goland ./myproject` to open GoLand)
- I got the plugin to work when I closed all my GoLand instances and reopened using my terminal (for me `gl ./myproject`)

Be sure to checkout https://github.com/a-h/templ/issues/127 as it might be the primary grounds for discussion.

**Comment by joerdav** [comment]
Yes I think the root cause to all of this is how Goland does not have access to your GOBIN var unless started from the terminal.

Ideally there would be a way to detect this, but at present we are just searching in places where you may have templ installed:

```
    Paths.get(System.getenv("GOBIN"), "templ"),
    Paths.get(System.getenv("GOBIN"), "templ.exe"),
    Paths.get(System.getenv("GOPATH"), "bin", "templ"),
    Paths.get(System.getenv("GOPATH"), "bin", "templ.exe"),
    Paths.get(System.getenv("GOROOT"), "bin", "templ"),
    Paths.get(System.getenv("GOROOT"), "bin", "templ.exe"),
    Paths.get(System.getenv("HOME"), "bin", "templ"),
    Paths.get(System.getenv("HOME"), "bin", "templ.exe"),
    Paths.get("/usr/local/bin/templ"),
    Paths.get("/usr/bin/templ"),
    Paths.get("/usr/local/go/bin/templ"),
    Paths.get("/usr/local/share/go/bin/templ"),
    Paths.get("/usr/share/go/bin/templ"),
```

Apologies for the delays in responding to these, I'm still getting to grips with both Jetbrains plugin dev and kotlin.

**Comment by joerdav** [comment]
I'm hoping that v8.0.0 will fix the problem for more people.

**Comment by yhc44** [comment]
I tried v8.0.0, but codecompletion is still not running on WSL2 (Windows 11 + Ubuntu 22.04)

Thank you for your effort.

**Comment by bastianwegge** [comment]
@yhc44 do you mind checking your IntelliJ/GoLand logs and maybe even posting them here? The problem might be that you don't have gopls installed, but that's a wild guess.

**Comment by m-poh** [comment]
IntelliJ 2023.3.2 and templ 0.0.8

```
java.lang.ExceptionInInitializerError
	at com.templ.templ.TemplSettings.getTemplLspPath(TemplSettings.kt:32)
	at com.templ.templ.TemplLspServerSupportProvider.fileOpened(TemplLspServerSupportProvider.kt:19)
	at com.intellij.platform.lsp.impl.LspServerManagerImpl$LspFileEditorManagerListener.V(LspServerManagerImpl.java:494)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:840)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:872)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:604)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:108)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:469)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:481)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.templ.templ.TemplLspServerSupportProviderKt.<clinit>(TemplLspServerSupportProvider.kt:39)
	... 33 more
```

**Comment by fcaps** [comment]
@yhc44 got autocomplete on wsl, see https://github.com/templ-go/templ-jetbrains/issues/5#issuecomment-1874034682

**Comment by joerdav** [comment]
The `getTemplLspPath` bug was fixed in the most recent version so hopefully that's a few more people fixed on this issue too.

**Comment by StanislavIvanovUULA** [comment]
GoLand 2023.2.5
Templ plugin 0.0.9
Macos 14.1.1

Auto complete still not working. Don't see any errors either

**Comment by joerdav** [comment]
Closing this one now since the fix was put in.
