### ISSUE TITLE
java.lang.ExceptionInInitializerError at com.templ.templ.TemplSettings.getTemplLspPath

### ISSUE THREAD

**Issue by PlusMinus0** [templ-go/templ-jetbrains#5]
Plugin version: 0.0.8
IDE: GoLand 2023.3.1
OS: Arch Linux x86_64
Kernel Version: 6.6.8-arch1-1
GOPATH: ~/go

```
$ `go env GOPATH`/bin/templ version
v0.2.501
```

Since the update to 0.0.8, the plugin crashes on startup. 

```
java.lang.ExceptionInInitializerError
	at com.templ.templ.TemplSettings.getTemplLspPath(TemplSettings.kt:32)
	at com.templ.templ.TemplLspServerSupportProvider.fileOpened(TemplLspServerSupportProvider.kt:19)
	at com.intellij.platform.lsp.impl.LspServerManagerImpl.F(LspServerManagerImpl.java:151)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:840)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:872)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:604)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:108)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:466)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:481)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.templ.templ.TemplLspServerSupportProviderKt.<clinit>(TemplLspServerSupportProvider.kt:39)
	... 33 more
```

**Comment by ssimk0** [comment]
Same issue on mac

Plugin version: 0.0.8
IDE: GoLand 2023.3.2
OS: MacOs 14.1.1
GOPATH: ~/go

**Comment by 2huBrulee** [comment]
I attempted to fix this in:  https://github.com/templ-go/templ-jetbrains/pull/6 

A workaround for current version would be:
- create a templ.xml inside the .idea directory in your project
- populate it with
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="TemplSettings">
    <option name="templLspPath" value="$USER_HOME$/go/bin/templ" />
  </component>
</project>
```
- change the value to point at your templ executable 
- restart goland

**Comment by oanogin** [comment]
I've fixed that by adding GOROOT, GOPATH, GOBIN to global env.

**Comment by fcaps** [comment]
not gonna lie, but getting this to work on wsl was not so easy.

**Issues encountered:**
1.  no config file. thx to @2huBrulee for providing a template
2. templ was executed on the host (windows) and not via the subsystem
3.  logs from lsp not displayed, would had helped 

**if you are working on windows and wsl, this may helps:**
1. install go on windows
2. install gopls via `go install golang.org/x/tools/gopls@latest` on windows
3. install templ via `go install github.com/a-h/templ/cmd/templ@latest` on windows
4. adjust the path in  `.idea/templ.xml` to templ on windows. you can find it with `get-command templ` in a powershell
5. test if the lsp is starting without exiting directly` templ lsp --log templ.log`. inspect the log for further troubleshooting (remember to start a new powershell session after installation)
6. restart goland and hope it will work

keeping the version in sync (host<->subsystem) is a meh, but this is only a workaround and maybe the maintainer has some ideas to fix this.

**Comment by joerdav** [comment]
Fixed in v0.0.9

**Comment by joerdav** [comment]
Please feel free to reopen if the problem persists.

**Comment by deitrix** [comment]
I'm still having a hard time getting this to work with WSL. I can't point GoLand at the WSL version of `templ` (located at `\\wsl$\Ubuntu-22.04\home\me\Projects\go\bin\templ`). This just yields a crash:
```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\\wsl$\Ubuntu-22.04\home\me\Projects\go\bin\templ": CreateProcess error=193, %1 is not a valid Win32 application
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:384)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.platform.lsp.api.LspServerDescriptor$startServerProcess$1.<init>(LspServerDescriptor.kt:104)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:104)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.kt:17)
	at com.intellij.platform.lsp.impl.LspServerImpl.C(LspServerImpl.kt:356)
	at com.intellij.platform.lsp.impl.LspServerImpl.C(LspServerImpl.kt:323)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Cannot run program "\\wsl$\Ubuntu-22.04\home\me\Projects\go\bin\templ": CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:469)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:374)
	... 19 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 23 more
```
I've tried as others suggest and installed templ and gopls on the host machine, but then I get a load of other errors like this
```
templ: 2024/09/15 19:29:26 go/packages.Load #9: err: exit status 1: stderr: go: RLock go.mod: Incorrect function. view_id="1" snapshot=5 directory=\\wsl$\Ubuntu-22.04\home\me\Projects\go\src\github.com\me\proj query=[file=\\wsl$\Ubuntu-22.04\home\me\Projects\go\src\github.com\me\proj\web\page\page_templ.go] packages=0 duration=429.5466ms
